//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class Key
    {
        public int Id { get; set; }
        public int NoteId { get; set; }
        public string KeyText { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
